touch ./data/problem1.in 
touch ./data/problem2.in 
touch ./data/problem3.in 
touch ./data/problem4.in 
touch ./data/problem5.in 
touch ./data/problem6.in 
touch ./data/problem7.in 
touch ./data/problem8.in 
touch ./data/problem9.in 
touch ./data/problem10.in 
